#pragma once

// Important includes, dont touch it
#include <Windows.h>
#include <Psapi.h>
#include <iostream>
#include <algorithm>
#include <functional>
#include <numeric>
#include <string>
#include <vector>
#include <time.h>
#include <random>
#include <sstream>
#include <fstream>
#include <iomanip>
#include <ctime>
#include <set>
#include <map>
#include <unordered_map>
#include <memory>
#include <thread>
#include <array>
#include <deque>
#include <intrin.h>
#include <atomic>
#include <mutex>
#include "bspflags.h"
#include "Hitboxes.h"
#include "Vector.h"
#include "Vector4D.h"
#include "dt_recv.h"
#include "VMatrix.h"
#include "Color.h"
#include "Vars.h"
#include "NetVarManager.h"
#include "Misc.h"
#include "Utils.h"
#include "C_BaseAnimating.h"
#include "Interfaces.h"
#include "Math.h"
